import Head from 'next/head'
import React, { useState, useEffect } from 'react'
export default function Home() {
  const [text, setText] = useState('')
  const [score, setScore] = useState(0)

  const analyzeSentiment = async () => {
    const res = await fetch('/api/sentiment', {
      method: 'POST',
      body: JSON.stringify({ text }),
      headers: {
        'Content-Type': 'application/json'
      }
    })
    const data = await res.json()
    setScore(data.score)
  }
  const submitHandler = async e => {
    e.preventDefault()
    await analyzeSentiment()
    setText('')
  }

  return (
    <div className="w-full min-h-screen bg-[#011f4b] text-[#b3cde0]">
      <Head>
        <title>Sentiment Analysis</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>

      <div className="max-w-3xl mx-auto px-5 py-10">
        <h1 className="text-center text-3xl font-bold">Sentiment Analysis</h1>
        <form onSubmit={submitHandler}>
          <div className="w-full my-3">
            <label
              htmlFor="text"
              className="w-full"
            >
              Text
            </label>
            <textarea
              className="w-full mt-3 px-3 py-2 text-gray-700 border rounded-lg focus:outline-none"
              placeholder="Your Text"
              name="text"
              value={text}
              onChange={e => setText(e.target.value)}
            ></textarea>
          </div>
          <button
            className="text-white bg-[#6497b1] px-5 py-2 rounded-lg"
            type="submit"
          >
            Analyze
          </button>
        </form>
        <div className="w-full flex justify-start items-center my-3">
          <p className="font-bold text-xl">Score:</p> <p> {score} </p>
        </div>
      </div>
    </div>
  )
}
