import Head from 'next/head'
import React, { useState, useEffect } from 'react'
import FrownIcon from '../components/icons/FrownIcon'
import SmileIcon from '../components/icons/SmileIcon'
import MehIcon from '../components/icons/MehIcon'
export default function Home() {
  const [text, setText] = useState('')
  const [score, setScore] = useState(null)

  const analyzeSentiment = async () => {
    const res = await fetch('/api/sentiment', {
      method: 'POST',
      body: JSON.stringify({ text }),
      headers: {
        'Content-Type': 'application/json'
      }
    })
    const data = await res.json()
    setScore(data.score)
  }
  const submitHandler = async e => {
    e.preventDefault()
    await analyzeSentiment()
  }

  return (
    <div className="w-full min-h-screen bg-[#011f4b] text-[#b3cde0]">
      <Head>
        <title>Sentiment Analysis</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>

      <div className="max-w-3xl px-5 py-10 mx-auto">
        <h1 className="text-3xl font-bold text-center">Sentiment Analysis</h1>
        <form onSubmit={submitHandler}>
          <div className="w-full my-3">
            <label
              htmlFor="text"
              className="w-full"
            >
              Enter Text
            </label>
            <textarea
              className="w-full px-3 py-2 mt-3 text-gray-700 border rounded-lg focus:outline-none"
              placeholder="Your Text"
              name="text"
              value={text}
              onChange={e => setText(e.target.value)}
            ></textarea>
          </div>
          <button
            className="text-white bg-[#6497b1] px-5 py-2 rounded-lg"
            type="submit"
          >
            Analyze
          </button>
        </form>
        <div className="flex items-center justify-start w-full my-3">
          <p className="text-xl font-bold">Score:</p> <p> {score} </p>
        </div>

        <div className="flex items-center justify-center w-full">
          {score > 0 && <SmileIcon />}
          {score === 0 && <MehIcon />}
          {score < 0 && <FrownIcon />}
        </div>
      </div>
    </div>
  )
}
